-- Test: TOTAL_FINANCIAL_EXPOSURE should equal TOTAL_PAYMENT_AMOUNT + TOTAL_PRESCRIPTION_COST
-- Validates the calculation logic in provider_360

select
    NPI,
    TOTAL_PAYMENT_AMOUNT,
    TOTAL_PRESCRIPTION_COST,
    TOTAL_FINANCIAL_EXPOSURE,
    (TOTAL_PAYMENT_AMOUNT + TOTAL_PRESCRIPTION_COST) as EXPECTED_EXPOSURE
from {{ ref('provider_360') }}
where TOTAL_FINANCIAL_EXPOSURE != (TOTAL_PAYMENT_AMOUNT + TOTAL_PRESCRIPTION_COST)
