{{ config(materialized='table') }}

WITH 
-- 1. Base provider (déjà unique via QUALIFY dans stg)
provider AS (
  SELECT * FROM {{ ref('provider') }}
  QUALIFY ROW_NUMBER() OVER (PARTITION BY NPI ORDER BY NPI_ENUMERATION_DATE DESC) = 1
),

-- 2. AGGRÉGER payments par NPI (fix multi-rows)
payments_agg AS (
  SELECT 
    NPI,
    COUNT(*) AS TOTAL_PAYMENTS,
    SUM(TOTAL_PAYMENT_AMOUNT) AS TOTAL_PAYMENT_AMOUNT,
    COUNT(DISTINCT PAYER_ID) AS UNIQUE_PAYERS,
    MAX(PCT_HIGH_RISK_PAYMENTS) AS PCT_HIGH_RISK_PAYMENTS,
    MAX(RECIPIENT_TIER) AS RECIPIENT_TIER,
    MIN(FIRST_PAYMENT_DATE) AS FIRST_PAYMENT_DATE,
    MAX(LAST_PAYMENT_DATE) AS LAST_PAYMENT_DATE
  FROM {{ ref('payments_summary') }} 
  GROUP BY 1
),

-- 3. AGGRÉGER prescriptions par NPI
prescriptions_agg AS (
  SELECT 
    NPI,
    COUNT(*) AS TOTAL_PRESCRIPTION_CLAIMS,
    SUM(TOTAL_COST) AS TOTAL_PRESCRIPTION_COST,
    COUNT(DISTINCT DRUG_NAME) AS UNIQUE_DRUGS_PRESCRIBED,
    MAX(PCT_BRAND_CLAIMS) AS PCT_BRAND_CLAIMS,
    MAX(PRESCRIBER_VOLUME_TIER) AS PRESCRIBER_VOLUME_TIER,
    SUM(TOTAL_HIGH_RISK_DRUGS) AS TOTAL_HIGH_RISK_DRUGS
  FROM {{ ref('prescriptions_summary') }} 
  GROUP BY 1
),

-- 4. Exclusions (déjà unique)
excluded AS (
  SELECT DISTINCT
    NPI, EXCLUSION_REASON, EXCLUSION_DATE, 
    IS_CURRENTLY_EXCLUDED, IS_HIGH_RISK AS IS_EXCLUDED_HIGH_RISK
  FROM {{ ref('excluded_providers') }} 
  WHERE NPI IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY NPI ORDER BY EXCLUSION_DATE DESC) = 1
)

-- 5. JOIN FINAL (tous uniques → 0 doublons !)
SELECT 
  p.NPI,
  p.ENTITY_TYPE, p.FULL_NAME, p.ORGANIZATION_NAME, p.CREDENTIAL, p.GENDER,
  p.CITY, p.STATE, p.ZIP_CODE, p.PHONE,
  p.SPECIALTY_CLASSIFICATION, p.SPECIALTY, p.PROVIDER_TYPE,
  p.IS_NPI_ACTIVE, p.NPI_ENUMERATION_DATE,
  
  -- Exclusions
  COALESCE(e.IS_CURRENTLY_EXCLUDED, FALSE) AS IS_EXCLUDED,
  e.EXCLUSION_REASON, e.EXCLUSION_DATE, e.IS_EXCLUDED_HIGH_RISK,
  
  -- Payments agrégés
  COALESCE(pay.TOTAL_PAYMENTS, 0) AS TOTAL_PAYMENTS,
  COALESCE(pay.TOTAL_PAYMENT_AMOUNT, 0) AS TOTAL_PAYMENT_AMOUNT,
  COALESCE(pay.UNIQUE_PAYERS, 0) AS UNIQUE_PAYERS,
  pay.RECIPIENT_TIER, COALESCE(pay.PCT_HIGH_RISK_PAYMENTS, 0) AS PCT_HIGH_RISK_PAYMENTS,
  pay.FIRST_PAYMENT_DATE, pay.LAST_PAYMENT_DATE,
  
  -- Prescriptions agrégés
  COALESCE(rx.TOTAL_PRESCRIPTION_CLAIMS, 0) AS TOTAL_PRESCRIPTION_CLAIMS,
  COALESCE(rx.TOTAL_PRESCRIPTION_COST, 0) AS TOTAL_PRESCRIPTION_COST,
  COALESCE(rx.UNIQUE_DRUGS_PRESCRIBED, 0) AS UNIQUE_DRUGS_PRESCRIBED,
  COALESCE(rx.PCT_BRAND_CLAIMS, 0) AS PCT_BRAND_CLAIMS,
  rx.PRESCRIBER_VOLUME_TIER, COALESCE(rx.TOTAL_HIGH_RISK_DRUGS, 0) AS TOTAL_HIGH_RISK_DRUGS,
  
  -- Flags
  CASE WHEN pay.NPI IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_PHARMA_PAYMENTS,
  CASE WHEN rx.NPI IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_PRESCRIPTIONS,
  
  -- KPI doc-conforme
  COALESCE(pay.TOTAL_PAYMENT_AMOUNT, 0) + COALESCE(rx.TOTAL_PRESCRIPTION_COST, 0) AS TOTAL_FINANCIAL_EXPOSURE,
  
  CURRENT_TIMESTAMP() AS _loaded_at

FROM provider p
LEFT JOIN payments_agg pay ON p.NPI = pay.NPI
LEFT JOIN prescriptions_agg rx ON p.NPI = rx.NPI
LEFT JOIN excluded e ON p.NPI = e.NPI