USE DATABASE FRAUDLENS_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE OPEN_PAYMENTS_OWNERSHIP
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION => '@BRONZE_S3_STAGE/open_payments/OP_DTL_OWNRSHP_PGYR2024_P06302025_06162025_LATEST.parquet',
        FILE_FORMAT => 'PARQUET_FORMAT'
    ))
);
