USE DATABASE FRAUDLENS_DB;
USE SCHEMA BRONZE;

COPY INTO OPEN_PAYMENTS_OWNERSHIP
FROM @BRONZE_S3_STAGE/open_payments/OP_DTL_OWNRSHP_PGYR2024_P06302025_06162025_LATEST.parquet
FILE_FORMAT = PARQUET_FORMAT
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
